apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chatapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-chatapp
          image: shahabadnan/chatapp-backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: production
            - name: MONGODB_URI
              value: "mongodb://admin:password@mongo-service:27017/dbname?authSource=admin"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chatapp-secret
                  key: jwt
            - name: PORT
              value: "5001"
